# Generated by Django 3.2.4 on 2021-10-22 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải đúng định dạng '0123 456 789'.", regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
