# Generated by Django 3.2.4 on 2021-10-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
