# Generated by Django 3.2.4 on 2021-11-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20211106_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.AddField(
            model_name='order',
            name='process',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
