# Generated by Django 3.2.4 on 2021-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20211106_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
