# Generated by Django 3.2.4 on 2022-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_order_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='process',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
